### ISSUE TITLE
Why you put room framework into Domain layer ? 

### ISSUE THREAD

**Issue by MtaufiqH** [ZahraHeydari/ArtGallery#5]
https://github.com/ZahraHeydari/Android-Clean-Architecture-MVVM-Hilt-RX/blob/56edd9bcfb849eba883a723a8c03277f1e8b9ecc/app/src/main/java/com/android/artgallery/domain/model/Photo.kt?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L6

I see in your code, you put a Room entity into a domain, that I know the domain is free from the outside or independent.

**Comment by ZahraHeydari** [comment]
You are totally right! Entities should not be in domain layer. They belong to data layer. I will fix it. Thanks for mentioning it.
